-- Comic Animator - Database Migration
-- Run this on your MySQL/MariaDB server

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(320) NOT NULL UNIQUE,
  `name` VARCHAR(255),
  `passwordHash` VARCHAR(255) NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastSignedIn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `projects` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `userId` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT 'Untitled Project',
  `aspectRatio` ENUM('9:16', '4:3') NOT NULL DEFAULT '9:16',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_projects_userId` (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `panels` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `projectId` INT NOT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `backgroundUrl` TEXT,
  `duration` FLOAT NOT NULL DEFAULT 3.0,
  `transition` ENUM('none','fade','slide-left','slide-right','zoom-in','zoom-out') NOT NULL DEFAULT 'fade',
  `transitionDuration` FLOAT NOT NULL DEFAULT 0.5,
  `panZoom` JSON,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_panels_projectId` (`projectId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `layers` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `panelId` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT 'Layer',
  `imageUrl` TEXT,
  `x` FLOAT NOT NULL DEFAULT 0,
  `y` FLOAT NOT NULL DEFAULT 0,
  `width` FLOAT NOT NULL DEFAULT 30,
  `height` FLOAT NOT NULL DEFAULT 50,
  `zIndex` INT NOT NULL DEFAULT 0,
  `flipX` INT NOT NULL DEFAULT 0,
  `animations` JSON,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_layers_panelId` (`panelId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
